/**
 * Seed Data for Website
 *
 * Used by seed.ts to populate the database.
 */

import type { games } from "#server/db/schema";

export const DEMO_ADMIN = {
  email: "admin@easyshop.com",
  password: "password123",
  name: "Demo Admin",
  role: "admin",
} as const;

export const DEMO_USER = {
  email: "demo@easyshop.com",
  password: "password123",
  name: "Demo User",
  role: "user",
} as const;

export const DATA: Omit<typeof games.$inferInsert, "id">[] = [
  {
    name: "Elden Ring",
    description:
      "Rise, Tarnished, and be guided by grace to brandish the power of Elden Ring and become an Elden Lord in the Lands Between. A vast world where open fields with a variety of situations and huge dungeons with complex and three-dimensional designs are seamlessly connected.",
    price: "59.99",
    imageUrl:
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header_292x136.jpg?t=1714569123",
    category: "Action RPG",
    stock: 999,
    developer: "FromSoftware",
    publisher: "Bandai Namco Entertainment",
    releaseDate: "2022-02-25",
    tags: ["Dark Fantasy", "Open World", "Souls-like", "RPG", "Difficult"],
    metacriticScore: 96,
    positiveReviews: 354821,
    negativeReviews: 12543,
    platforms: ["windows"],
    videoUrl: "https://www.youtube.com/embed/QH2-TGUlwu4",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/ss_2.jpg",
    ],
  },
  {
    name: "Baldur's Gate 3",
    description:
      "Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival, and the lure of absolute power. Mysterious abilities are awakening inside you, drawn from a mind flayer parasite planted in your brain.",
    price: "59.99",
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg?t=1714569456",
    category: "RPG",
    stock: 999,
    developer: "Larian Studios",
    publisher: "Larian Studios",
    releaseDate: "2023-08-03",
    tags: ["RPG", "Turn-based", "Co-op", "Fantasy", "Story Rich"],
    metacriticScore: 96,
    positiveReviews: 482156,
    negativeReviews: 8723,
    platforms: ["windows", "mac"],
    videoUrl: "https://www.youtube.com/embed/1eq4lR6N4qg",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/ss_2.jpg",
    ],
  },
  {
    name: "Cyberpunk 2077: Phantom Liberty",
    description:
      "Cyberpunk 2077 is an open-world, action-adventure RPG set in the megalopolis of Night City, where you play as a cyberpunk mercenary wrapped up in a do-or-die fight for survival. Phantom Liberty is a new spy-thriller adventure.",
    price: "49.99",
    originalPrice: "59.99",
    discountPercent: 17,
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg?t=1714569876",
    category: "Action",
    stock: 999,
    developer: "CD PROJEKT RED",
    publisher: "CD PROJEKT RED",
    releaseDate: "2023-09-26",
    tags: ["Open World", "Cyberpunk", "Sci-Fi", "Action RPG", "Story Rich"],
    metacriticScore: 86,
    positiveReviews: 412345,
    negativeReviews: 89234,
    platforms: ["windows"],
    videoUrl: "https://www.youtube.com/embed/8X2kIfS6fb8",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/ss_2.jpg",
    ],
  },
  {
    name: "Stardew Valley",
    description:
      "You've inherited your grandfather's old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life. Can you learn to live off the land and turn these overgrown fields into a thriving home?",
    price: "14.99",
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg?t=1714570123",
    category: "Simulation",
    stock: 999,
    developer: "ConcernedApe",
    publisher: "ConcernedApe",
    releaseDate: "2016-02-26",
    tags: ["Farming", "Life Sim", "Co-op", "Relaxing", "Pixel Graphics"],
    metacriticScore: 93,
    positiveReviews: 389456,
    negativeReviews: 6234,
    platforms: ["windows", "mac", "linux"],
    videoUrl: "https://www.youtube.com/embed/OF2C6jotlfc",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/ss_2.jpg",
    ],
  },
  {
    name: "Hollow Knight",
    description:
      "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, ancient cities and deadly wastes; battle tainted creatures and befriend bizarre bugs.",
    price: "14.99",
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/367520/header.jpg?t=1714570567",
    category: "Metroidvania",
    stock: 999,
    developer: "Team Cherry",
    publisher: "Team Cherry",
    releaseDate: "2017-02-24",
    tags: ["Metroidvania", "2D", "Difficult", "Atmospheric", "Dark"],
    metacriticScore: 90,
    positiveReviews: 234567,
    negativeReviews: 4521,
    platforms: ["windows", "mac", "linux"],
    videoUrl: "https://www.youtube.com/embed/42YQzRME-Ec",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/367520/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/367520/ss_2.jpg",
    ],
  },
  {
    name: "Hades",
    description:
      "Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler from the creators of Bastion, Transistor, and Pyre. Play as Zagreus, son of Hades, and escape the Greek underworld.",
    price: "24.99",
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/header.jpg?t=1714570890",
    category: "Roguelike",
    stock: 999,
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    releaseDate: "2020-09-17",
    tags: ["Roguelike", "Action", "Indie", "Mythology", "Story Rich"],
    metacriticScore: 93,
    positiveReviews: 198234,
    negativeReviews: 3123,
    platforms: ["windows", "mac", "linux"],
    videoUrl: "https://www.youtube.com/embed/3OjJr0hM3iM",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/ss_2.jpg",
    ],
  },
  {
    name: "Red Dead Redemption 2",
    description:
      "America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America.",
    price: "39.99",
    originalPrice: "59.99",
    discountPercent: 33,
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg?t=1714571234",
    category: "Action Adventure",
    stock: 999,
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    releaseDate: "2019-12-05",
    tags: ["Open World", "Western", "Story Rich", "Multiplayer", "Third-Person"],
    metacriticScore: 97,
    positiveReviews: 345678,
    negativeReviews: 34567,
    platforms: ["windows"],
    videoUrl: "https://www.youtube.com/embed/eaW0T0Uixc",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/ss_2.jpg",
    ],
  },
  {
    name: "God of War",
    description:
      "His vengeance against the Gods of Olympus years behind him, Kratos now lives as a man in the realm of Norse Gods and monsters. It is in this harsh, unforgiving world that he must fight to survive and teach his son to do the same.",
    price: "49.99",
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/header.jpg?t=1714571567",
    category: "Action Adventure",
    stock: 999,
    developer: "Santa Monica Studio",
    publisher: "Sony Interactive Entertainment",
    releaseDate: "2022-01-14",
    tags: ["Action", "Mythology", "Story Rich", "Third-Person", "Singleplayer"],
    metacriticScore: 94,
    positiveReviews: 289456,
    negativeReviews: 12456,
    platforms: ["windows"],
    videoUrl: "https://www.youtube.com/embed/FyIwLFX5Abo",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/ss_2.jpg",
    ],
  },
  {
    name: "Sekiro: Shadows Die Twice",
    description:
      "Carve your own clever path to vengeance in an all-new adventure from developer FromSoftware. Explore late 1500s Sengoku Japan, a brutal period of constant life and death conflict, as you come face to face with larger than life foes.",
    price: "59.99",
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/814380/header.jpg?t=1714571890",
    category: "Action",
    stock: 999,
    developer: "FromSoftware",
    publisher: "Activision",
    releaseDate: "2019-03-22",
    tags: ["Action", "Souls-like", "Ninja", "Difficult", "Historical"],
    metacriticScore: 90,
    positiveReviews: 178234,
    negativeReviews: 18234,
    platforms: ["windows"],
    videoUrl: "https://www.youtube.com/embed/C8bMVDcAi6k",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/814380/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/814380/ss_2.jpg",
    ],
  },
  {
    name: "The Witcher 3: Wild Hunt - Complete Edition",
    description:
      "As war rages on throughout the Northern Realms, you take on the greatest contract of your life — tracking down the Child of Prophecy, a living weapon that can alter the shape of the world. Includes all DLCs and expansions.",
    price: "39.99",
    originalPrice: "49.99",
    discountPercent: 20,
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg?t=1714572234",
    category: "RPG",
    stock: 999,
    developer: "CD PROJEKT RED",
    publisher: "CD PROJEKT RED",
    releaseDate: "2015-05-18",
    tags: ["Open World", "RPG", "Fantasy", "Story Rich", "Third-Person"],
    metacriticScore: 93,
    positiveReviews: 456789,
    negativeReviews: 23456,
    platforms: ["windows"],
    videoUrl: "https://www.youtube.com/embed/XdtP9d9lX-k",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/ss_2.jpg",
    ],
  },
  {
    name: "Persona 5 Royal",
    description:
      "Step into the shoes of a high school student in Tokyo with a secret double life as a Phantom Thief. Balance your daily life, form relationships, and steal the twisted desires of corrupt adults to reform society.",
    price: "59.99",
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1687950/header.jpg?t=1714572567",
    category: "RPG",
    stock: 999,
    developer: "ATLUS",
    publisher: "SEGA",
    releaseDate: "2022-10-21",
    tags: ["RPG", "Anime", "Turn-based", "Story Rich", "School"],
    metacriticScore: 95,
    positiveReviews: 234567,
    negativeReviews: 6789,
    platforms: ["windows"],
    videoUrl: "https://www.youtube.com/embed/1fK5Ml-QXR8",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1687950/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1687950/ss_2.jpg",
    ],
  },
  {
    name: "Monster Hunter World: Iceborne",
    description:
      "Master the beast hunting experience with Monster Hunter World: Iceborne. Explore a new snow-covered region, face ferocious new monsters, and wield new weapons and armor in this massive expansion.",
    price: "39.99",
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/582010/header.jpg?t=1714572890",
    category: "Action",
    stock: 999,
    developer: "CAPCOM CO., LTD.",
    publisher: "CAPCOM CO., LTD.",
    releaseDate: "2020-01-09",
    tags: ["Action", "Co-op", "Open World", "Multiplayer", "Hunting"],
    metacriticScore: 90,
    positiveReviews: 234123,
    negativeReviews: 34567,
    platforms: ["windows"],
    videoUrl: "https://www.youtube.com/embed/nlH5gT9Dq1A",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/582010/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/582010/ss_2.jpg",
    ],
  },
  {
    name: "Terraria",
    description:
      "Dig, fight, explore, build: The world is your playground as you craft weapons, armor, and more. Build your own city, explore vast underground caverns, and battle hundreds of unique enemies in this 2D sandbox adventure.",
    price: "9.99",
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/105600/header.jpg?t=1714573234",
    category: "Sandbox",
    stock: 999,
    developer: "Re-Logic",
    publisher: "Re-Logic",
    releaseDate: "2011-05-16",
    tags: ["Sandbox", "2D", "Crafting", "Multiplayer", "Survival"],
    metacriticScore: 95,
    positiveReviews: 567890,
    negativeReviews: 18234,
    platforms: ["windows", "mac", "linux"],
    videoUrl: "https://www.youtube.com/embed/6rS5s2p2aQk",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/105600/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/105600/ss_2.jpg",
    ],
  },
  {
    name: "Valheim",
    description:
      "A brutal exploration and survival game for 1-10 players, set in a procedurally-generated purgatory inspired by Viking culture. Battle, build, and conquer your way to a saga worthy of Odin's patronage!",
    price: "19.99",
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/892970/header.jpg?t=1714573567",
    category: "Survival",
    stock: 999,
    developer: "Iron Gate AB",
    publisher: "Coffee Stain Publishing",
    releaseDate: "2021-02-02",
    tags: ["Survival", "Crafting", "Viking", "Open World", "Multiplayer"],
    metacriticScore: 85,
    positiveReviews: 298765,
    negativeReviews: 34123,
    platforms: ["windows"],
    videoUrl: "https://www.youtube.com/embed/w5xh4kL9Y6c",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/892970/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/892970/ss_2.jpg",
    ],
  },
  {
    name: "Among Us",
    description:
      "Play with 4-15 player online or via local WiFi as you attempt to prepare your spaceship for departure, but beware as one will be an impostor bent on killing everyone. Find the impostor, complete tasks, and vote to eject the suspect.",
    price: "4.99",
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/945360/header.jpg?t=1714573890",
    category: "Party",
    stock: 999,
    developer: "InnerSloth LLC",
    publisher: "InnerSloth LLC",
    releaseDate: "2018-11-16",
    tags: ["Multiplayer", "Party", "Social Deduction", "Funny", "Online Co-op"],
    metacriticScore: 80,
    positiveReviews: 567890,
    negativeReviews: 89012,
    platforms: ["windows", "mac"],
    videoUrl: "https://www.youtube.com/embed/NW091H0nK0o",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/945360/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/945360/ss_2.jpg",
    ],
  },
  {
    name: "Portal 2",
    description:
      "The single-player portion of Portal 2 introduces a cast of dynamic new characters, a host of fresh puzzle elements, and a much larger set of devious test chambers. Players will explore never-before-seen areas of the Aperture Science Labs.",
    price: "9.99",
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/620/header.jpg?t=1714574234",
    category: "Puzzle",
    stock: 999,
    developer: "Valve",
    publisher: "Valve",
    releaseDate: "2011-04-19",
    tags: ["Puzzle", "Co-op", "First-Person", "Sci-Fi", "Comedy"],
    metacriticScore: 95,
    positiveReviews: 423456,
    negativeReviews: 5123,
    platforms: ["windows", "mac", "linux"],
    videoUrl: "https://www.youtube.com/embed/S2p0-0M1GvY",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/620/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/620/ss_2.jpg",
    ],
  },
  {
    name: "Factorio",
    description:
      "Factorio is a game about building and maintaining factories. You will be mining resources, researching technologies, building infrastructure, automating production and fighting enemies. Use your imagination to design your factory.",
    price: "29.99",
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/427520/header.jpg?t=1714574567",
    category: "Simulation",
    stock: 999,
    developer: "Wube Software",
    publisher: "Wube Software",
    releaseDate: "2020-08-14",
    tags: ["Simulation", "Automation", "Building", "Strategy", "Survival"],
    metacriticScore: 91,
    positiveReviews: 123456,
    negativeReviews: 5678,
    platforms: ["windows", "mac", "linux"],
    videoUrl: "https://www.youtube.com/embed/Qu_I96JU7r0",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/427520/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/427520/ss_2.jpg",
    ],
  },
  {
    name: "Darkest Dungeon",
    description:
      "Darkest Dungeon is a challenging gothic roguelike turn-based RPG about the psychological stresses of adventuring. Recruit, train, and lead a team of flawed heroes through twisted forests, forgotten warrens, ruined crypts, and beyond.",
    price: "24.99",
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/262060/header.jpg?t=1714574890",
    category: "Roguelike",
    stock: 999,
    developer: "Red Hook Studios",
    publisher: "Red Hook Studios",
    releaseDate: "2016-01-19",
    tags: ["Roguelike", "Turn-based", "Gothic", "Difficult", "Dark"],
    metacriticScore: 84,
    positiveReviews: 134567,
    negativeReviews: 18234,
    platforms: ["windows", "mac", "linux"],
    videoUrl: "https://www.youtube.com/embed/4XgXG5aS3wY",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/262060/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/262060/ss_2.jpg",
    ],
  },
  {
    name: "Doom Eternal",
    description:
      "Hell's armies have invaded Earth. Become the Slayer in an epic single-player campaign to conquer demons across dimensions and stop the final destruction of humanity. The only thing they fear... is you.",
    price: "29.99",
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/782330/header.jpg?t=1714575234",
    category: "FPS",
    stock: 999,
    developer: "id Software",
    publisher: "Bethesda Softworks",
    releaseDate: "2020-03-20",
    tags: ["FPS", "Action", "Demons", "Fast-Paced", "Shooter"],
    metacriticScore: 88,
    positiveReviews: 156789,
    negativeReviews: 18234,
    platforms: ["windows", "mac", "linux"],
    videoUrl: "https://www.youtube.com/embed/V008I0a2G1s",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/782330/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/782330/ss_2.jpg",
    ],
  },
  {
    name: "Vampire Survivors",
    description:
      "Mow down thousands of night creatures and survive until daylight! This roguelike time attack game with minimal gameplay is all about choosing the right path and upgrades. Unlock new characters and weapons as you progress.",
    price: "4.99",
    imageUrl: "https://cdn.cloudflare.steamstatic.com/steam/apps/1794680/header.jpg?t=1714575567",
    category: "Roguelike",
    stock: 999,
    developer: "Poncle",
    publisher: "Poncle",
    releaseDate: "2022-10-20",
    tags: ["Roguelike", "Bullet Hell", "Survival", "Indie", "Retro"],
    metacriticScore: 89,
    positiveReviews: 345678,
    negativeReviews: 6789,
    platforms: ["windows"],
    videoUrl: "https://www.youtube.com/embed/gWb8Y1w7p3Y",
    screenshots: [
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1794680/ss_1.jpg",
      "https://cdn.cloudflare.steamstatic.com/steam/apps/1794680/ss_2.jpg",
    ],
  },
];
